/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visoes;

/**
 *
 * @author willh
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sistemaDesktop = new visoes.SistemaDesktop();
        jMenuBar = new javax.swing.JMenuBar();
        menuCliente = new javax.swing.JMenu();
        itemListarCliente = new javax.swing.JMenuItem();
        menuCargo = new javax.swing.JMenu();
        itemListarCargo = new javax.swing.JMenuItem();
        menuFornecedor = new javax.swing.JMenu();
        itemListarFornecedor = new javax.swing.JMenuItem();
        menuSetor = new javax.swing.JMenu();
        itemListarSetor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCliente.setText("Clientes");

        itemListarCliente.setText("Mostrar...");
        itemListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(itemListarCliente);

        jMenuBar.add(menuCliente);

        menuCargo.setText("Cargos");

        itemListarCargo.setText("Mostrar...");
        itemListarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarCargoActionPerformed(evt);
            }
        });
        menuCargo.add(itemListarCargo);

        jMenuBar.add(menuCargo);

        menuFornecedor.setText("Fornecedores");

        itemListarFornecedor.setText("Mostrar...");
        itemListarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarFornecedorActionPerformed(evt);
            }
        });
        menuFornecedor.add(itemListarFornecedor);

        jMenuBar.add(menuFornecedor);

        menuSetor.setText("Setores");

        itemListarSetor.setText("Mostrar...");
        itemListarSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarSetorActionPerformed(evt);
            }
        });
        menuSetor.add(itemListarSetor);

        jMenuBar.add(menuSetor);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sistemaDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sistemaDesktop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarClienteActionPerformed
        sistemaDesktop.abrirJanelaListarClientes();
    }//GEN-LAST:event_itemListarClienteActionPerformed

    private void itemListarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarCargoActionPerformed
        sistemaDesktop.abrirJanelaListarCargos();
    }//GEN-LAST:event_itemListarCargoActionPerformed

    private void itemListarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarFornecedorActionPerformed
       sistemaDesktop.abrirJanelaListarFornecedores();
    }//GEN-LAST:event_itemListarFornecedorActionPerformed

    private void itemListarSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarSetorActionPerformed
        sistemaDesktop.abrirJanelaListarSetores();
    }//GEN-LAST:event_itemListarSetorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemListarCargo;
    private javax.swing.JMenuItem itemListarCliente;
    private javax.swing.JMenuItem itemListarFornecedor;
    private javax.swing.JMenuItem itemListarSetor;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu menuCargo;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuFornecedor;
    private javax.swing.JMenu menuSetor;
    private visoes.SistemaDesktop sistemaDesktop;
    // End of variables declaration//GEN-END:variables
}
