/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author willh
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sistemaDesktop = new view.SistemaDesktop();
        jMenuBar = new javax.swing.JMenuBar();
        menuCliente = new javax.swing.JMenu();
        itemListarCliente = new javax.swing.JMenuItem();
        itemCriarCliente = new javax.swing.JMenuItem();
        menuCargo = new javax.swing.JMenu();
        itemListarCargo = new javax.swing.JMenuItem();
        itemCriarCargo = new javax.swing.JMenuItem();
        menuFornecedor = new javax.swing.JMenu();
        itemListarFornecedor = new javax.swing.JMenuItem();
        itemCriarFornecedor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCliente.setText("Clientes");

        itemListarCliente.setText("Mostrar existentes");
        menuCliente.add(itemListarCliente);

        itemCriarCliente.setText("Criar novo");
        menuCliente.add(itemCriarCliente);

        jMenuBar.add(menuCliente);

        menuCargo.setText("Clientes");

        itemListarCargo.setText("Mostrar existentes");
        menuCargo.add(itemListarCargo);

        itemCriarCargo.setText("Criar novo");
        menuCargo.add(itemCriarCargo);

        jMenuBar.add(menuCargo);

        menuFornecedor.setText("Clientes");

        itemListarFornecedor.setText("Mostrar existentes");
        menuFornecedor.add(itemListarFornecedor);

        itemCriarFornecedor.setText("Criar novo");
        menuFornecedor.add(itemCriarFornecedor);

        jMenuBar.add(menuFornecedor);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sistemaDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sistemaDesktop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCriarCargo;
    private javax.swing.JMenuItem itemCriarCliente;
    private javax.swing.JMenuItem itemCriarFornecedor;
    private javax.swing.JMenuItem itemListarCargo;
    private javax.swing.JMenuItem itemListarCliente;
    private javax.swing.JMenuItem itemListarFornecedor;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu menuCargo;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuFornecedor;
    private view.SistemaDesktop sistemaDesktop;
    // End of variables declaration//GEN-END:variables
}
